doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        # configure these for your database server
        url: "%env(resolve:DATABASE_URL)%"
        driver: "pdo_mysql"
        server_version: "5.7"
        charset: utf8mb4
      Bulk:
        # configure these for your database server
        url: "%env(resolve:DATABASE_BULK_URL)%"
        driver: "pdo_mysql"
        server_version: "5.7"
        charset: utf8mb4
      Account:
        # configure these for your database server
        url: "%env(resolve:DATABASE_ACCOUNT_URL)%"
        driver: "pdo_mysql"
        server_version: "5.7"
        charset: utf8mb4
      User:
        # configure these for your database server
        url: "%env(resolve:DATABASE_USER_URL)%"
        driver: "pdo_mysql"
        server_version: "5.7"
        charset: utf8mb4
      Route:
        # configure these for your database server
        url: "%env(resolve:DATABASE_ROUTE_URL)%"
        driver: "pdo_mysql"
        server_version: "5.7"
        charset: utf8mb4
      Licence:
        # configure these for your database server
        url: "%env(resolve:DATABASE_LICENCE_URL)%"
        driver: "pdo_mysql"
        server_version: "5.7"
        charset: utf8mb4
      Vitrine:
        # configure these for your database server
        url: "%env(resolve:DATABASE_VITRINE_URL)%"
        driver: "pdo_mysql"
        server_version: "5.7"
        charset: utf8mb4
      Pub:
        # configure these for your database server
        url: "%env(resolve:DATABASE_PUB_URL)%"
        driver: "pdo_mysql"
        server_version: "5.7"
        charset: utf8mb4

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    default_entity_manager: default
    #auto_generate_proxy_classes: false
    #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    #auto_mapping: true
    #mappings:
    #    App:
    #        is_bundle: false
    #        dir: '%kernel.project_dir%/src/Entity'
    #        prefix: 'App\Entity'
    #        alias: App
    #proxy_namespace: Proxies
    entity_managers:
      default:
        connection: default
        mappings:
          Auth:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity/Auth"
            prefix: 'App\Entity\Auth'
            alias: Auth
      Bulk:
        connection: Bulk
        mappings:
          Bulk:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity/Bulk"
            prefix: 'App\Entity\Bulk'
            alias: Bulk
      Account:
        connection: Account
        mappings:
          Account:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity/Account"
            prefix: 'App\Entity\Account'
            alias: Account
      User:
        connection: User
        mappings:
          User:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity/User"
            prefix: 'App\Entity\User'
            alias: User
      Route:
        connection: Route
        mappings:
          Route:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity/Route"
            prefix: 'App\Entity\Route'
            alias: Route
      Licence:
        connection: Licence
        mappings:
          Licence:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity/Licence"
            prefix: 'App\Entity\Licence'
            alias: Licence
      Vitrine:
        connection: Vitrine
        mappings:
          Vitrine:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity/Vitrine"
            prefix: 'App\Entity\Vitrine'
            alias: Vitrine
      Pub:
        connection: Pub
        mappings:
          Pub:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity/Pub"
            prefix: 'App\Entity\Pub'
            alias: Pub

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
