gesdinet_jwt_refresh_token:
  ttl: 2592000
  ttl_update: true
  token_parameter_name: refreshToken
  user_identity_field: phone
  # firewall: api
  refresh_token_class: App\Entity\Auth\JwtRefreshToken
