#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_auth:
  path: /api/auth
  methods: ["POST"]

api_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
